### ISSUE TITLE
Extension isn't packed ready for install

### ISSUE THREAD

**Issue by lukecarbis** [FourPi/trello-card-numbers-safari#1]
The extension displays as a folder in MacOs High Sierra, and can't be installed in Safari with default settings.

**Comment by lukecarbis** [comment]
Installation instructions:

1. In Safari > Preferences > Advanced, turn on **Show Develop menu in menu bar**
2. Choose the menu item Develop > Show Extension Builder
3. In the bottom left corner, click the + icon, and then Add Extension…
4. Choose the `trello-card-numbers.safariextension` folder
5. In the top left corner, press the Install button

**Comment by beeradmoore** [comment]
Wasn't really documented, but yeah thats how it should be used. Has not been published to the store yet either as its a bit of a WIP. Ill add those install instructions to the readme later to let others know how to use it. Cheers!

**Comment by vender98** [comment]
Hi @beeradmoore !
Is it still possible to install the extension on macOS Big Sur 11.1 ?
The [instruction](https://github.com/FourPi/trello-card-numbers-safari/issues/1#issuecomment-357551903) provided by @lukecarbis no longer works, because the option "Show Extension Builder" no longer appears in "Develop" menu.

**Comment by beeradmoore** [comment]
Hey @vender98 , with Safari 14 I think they changed how extensions work so this is no longer compatible.

Unfortunately we had not tried as we no longer use Trello.

**Comment by vender98** [comment]
@beeradmoore what a pity :(
Thanks !
